title: Ernesto Salgado, Senior Backend Engineer
logo: /assets/img/ess.png
description: Ernesto Salgado Su√°rez, Senior Backend Engineer.
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme